config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
 root to: "homes#index"
 get 'homes/about'
 post '/homes/guest_sign_in', to: 'homes#new_guest'
 get 'tweets/search'

 resources :tweets, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
   resource :favorites, only: [:create, :destroy]
   resources :tweet_comments, only: [:create, :destroy]
 end
 resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :following, :followers
      end
    end
 resources :relationships, only: [:create, :destroy]
 resources :notifications, only: [:index, :destroy]


end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user
  attachment :image
  has_many :tweet_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_many :favorites, dependent: :destroy

  validates :body, presence: true

# いいね機能
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def create_notification_by(current_user)
        notification = current_user.active_notifications.new(
          tweet_id: id,
          visited_id: user_id,
          action: "favorite"
        )
        notification.save if notification.valid?
  end
# 通知機能
  def create_notification_comment!(current_user, comment_id)
        # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
        temp_ids = TweetComment.select(:user_id).where(tweet_id: id).where.not(user_id: current_user.id).distinct
        temp_ids.each do |temp_id|
            save_notification_comment!(current_user, comment_id, temp_id['user_id'])
        end
        # まだ誰もコメントしていない場合は、投稿者に通知を送る
        save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, tweet_comment_id, visited_id)
        # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
        notification = current_user.active_notifications.new(
          tweet_id: id,
          tweet_comment_id: tweet_comment_id,
          visited_id: visited_id,
          action: 'tweet_comment'
        )
        # 自分の投稿に対するコメントの場合は、通知済みとする
        if notification.visiter_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
  end

  def self.search(search)
      if search
        Tweet.where(['body LIKE ?', "%#{search}%"])
      else
        Tweet.all
      end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
    redirect_to tweets_path,notice: 'つぶやきました。'
    else
      render 'new'
    end
  end

  def index
    @tweets = Tweet.page(params[:page]).reverse_order
    # @user = User.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
  end

  def edit
     @tweet = Tweet.find(params[:id])
     if @tweet.user != current_user
      redirect_to tweet_path, alert: '不正なアクセスです。'
     end
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweet_path(@tweet), notice: "つぶやきを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end
  
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @tweets = Tweet.search(params[:search])
  end
  
  private

  def tweet_params
    params.require(:tweet).permit(:image, :body)
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_favorites.html.erb
<% if tweet.favorited_by?(current_user) %>
                <p>
                <%= link_to tweet_favorites_path(tweet), method: :delete, remote: true do %>
                ♥<%= tweet.favorites.count %> いいね
                <% end %>
                </p>
                <% else %>
                <p>
                <%= link_to tweet_favorites_path(tweet), method: :post, remote: true do %>
                ♡<%= tweet.favorites.count %> いいね
                <% end %>
                </p>
 <% end %>

app/views/tweets/create.js.erb
$("#favorite-btn_<%= @tweets.id %>").html("<%= j(render 'tweets/favorites', tweet: tweet) %>");

app/views/tweets/edit.html.erb
<section class="hero is-small is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        つぶやき編集
      </h1>
    </div>
  </div>
</section>

<% if @tweet.errors.any? %>
  <div class="notification is-danger">
    <ul>
      <% @tweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @tweet do |f| %>
          <div class="field">
            <%= f.label :body, "内容", class: "label" %>
            <%= f.text_area :body, rows:'10', class: "textarea" %>
          </div>
            <%= f.submit '投稿', class: "button is-dark is-outlined" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/tweets/index.html.erb
<section class="hero is-small is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-white">
        投稿一覧
      </h1>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <p>投稿検索</p>
    　　　<%= form_tag(tweets_search_path,:method => 'get') do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索', :body => nil %>
        <% end %>
    </div>
　</div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @tweets.each do |tweet| %>
        <div class="column is-4">
          <div class="card">
            <p class="image is-64x64"><%= attachment_image_tag tweet.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg",class: "is-rounded" %></p>
            <p><%= link_to tweet.user.name, user_path(tweet.user.id) %></p>
            <%= link_to tweet_path(tweet.id) do %>
            <p><%= tweet.body %></p>
            <% end %>
              <div class="card-image">
                <figure class="image is-2by1">
                  <%= link_to tweet_path(tweet) do %>
                  <%= attachment_image_tag tweet, :image,fallback: "no_image.jpg" %>
                  <% end %>
                </figure>
              </div>
　　　　　　  <!--いいね機能-->
              <%= render "tweets/favorites", tweet: tweet%>
              <p><%= link_to "#{tweet.tweet_comments.count} コメント", tweet_path(tweet.id) %></p>
              <%= render "relationships/follow_button", user: tweet.user %>
             </div>
           </div>
           <% end %>
           <!--フォロー機能-->
           <%= paginate @tweets %>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<section class="hero is-small is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規投稿
      </h1>
    </div>
  </div>
</section>

<% if @tweet.errors.any? %>
  <div class="notification is-danger">
    <ul>
      <% @tweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @tweet do |f| %>
          <div class="field">
            <%= f.label :body, "つぶやき", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-dark is-outlined" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/tweets/search.html.erb
  <section class="hero is-small is-link">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-white">
        検索結果
      </h1>
      </div>
    </div>
  </div>
</section>

  <section class="section">
  <div class="container">
    <div class="columns is-multiline">
    <% @tweets.each do |tweet| %>
      <div class="column is-4">
          <div class="card">
          <p class="image is-64x64"><%= attachment_image_tag tweet.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",class: "is-rounded" %></p>
          <p><%= link_to tweet.user.name, user_path(tweet.user.id) %></p>
          <%= link_to tweet_path(tweet.id) do %>
            <p><%= tweet.body %></p>
          <% end %>
          <div class="card-image">
              <figure class="image is-2by1">
                <%= link_to tweet_path(tweet) do %>
              <%= attachment_image_tag tweet, :image,fallback: "no_image.jpg" %>
              <% end %>
            </figure>
          </div>
　　　　　　<!--いいね機能-->
           <%= render "tweets/favorites", tweet: tweet%>

         <p><%= link_to "#{tweet.tweet_comments.count} コメント", tweet_path(tweet.id) %></p>
          <%= render "relationships/follow_button", user: tweet.user %>
        </div>
      </div>
    <% end %>
    <!--フォロー機能-->
    <%#= paginate @tweets %>
    </div>
   </div>
 </section>

app/views/tweets/show.html.erb
<section class="hero is-small is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        つぶやき
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <div class="card-content">
              <div class="media">
              　<div class="media-content">
                  <div class="colums">
                    <div class="colum">
                      <p class="image is-64x64"><%= attachment_image_tag @tweet.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg",class: "is-rounded" %></p>
                  　　<P><%= @tweet.user.name %></P>
                    　<p><%= @tweet.body %></p>
                    　  <figure class="image is-2by1">
                        <%= attachment_image_tag @tweet, :image, fallback: "no_image.jpg"  %>
                       </figure>
                      <p>投稿日時：<%= @tweet.created_at.strftime('%Y/%m/%d') %></p>

                      <% if @tweet.user.id == current_user.id %>
                      <%= link_to "編集画面へ", edit_tweet_path(@tweet), class: "button is-success" %>
                      <% end %>
                      <% if @tweet.user == current_user %>
                      <%= link_to "削除", tweet_path(@tweet), method: :delete, data: {confirm: "削除しますか？"}, class: "button is-success" %>
                      <% end %>

                     <%= render "tweets/favorites",tweet: @tweet%>
                     <p>コメント件数：<%= @tweet.tweet_comments.count %></p>
                   </div>
                  </div>
                </div>
              </div>
              <% @tweet.tweet_comments.each do |tweet_comment| %>
                <div class="columns">
                  <div class="column">
                     <p class="image is-64x64"><%= attachment_image_tag tweet_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",class: "is-rounded" %></p>
                  </div>
                  <div class="column is-3">
                    <%= tweet_comment.user.name %>
                  </div>
                  <div class="column is-4">
                    <%= tweet_comment.comment %>
                  </div>
                  <div class="column">
                    <%= tweet_comment.created_at.strftime('%Y/%m/%d') %>
                  </div>
                  <div class="column">
                    <% if tweet_comment.user == current_user %>
                  </div>
                  <div class="column">
                    <div class="comment-delete">
                      <%= link_to "削除", tweet_tweet_comment_path(tweet_comment.tweet, tweet_comment), method: :delete, data: {confirm: "削除しますか？"}, class: "button is-success" %>
                      <% end %>
                      <% end %>
                    </div>
                 </div>
              </div>
                <%= form_with(model:[@tweet, @tweet_comment], local: true) do |f| %>
                <%= f.text_area :comment, rows:'10',placeholder: "コメントをここに",class: "textarea" %>
                <%= f.submit "送信する", class: "button is-success" %>
              　<% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>