config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
 root to: "homes#index"
 get 'homes/about'
 post '/homes/guest_sign_in', to: 'homes#new_guest'
 get 'tweets/search'

 resources :tweets, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
   resource :favorites, only: [:create, :destroy]
   resources :tweet_comments, only: [:create, :destroy]
 end
 resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :following, :followers
      end
    end
 resources :relationships, only: [:create, :destroy]
 resources :notifications, only: [:index, :destroy]


end

app/models/notification.rb
class Notification < ApplicationRecord

  #スコープ(新着順)
    default_scope->{order(created_at: :desc)}

    belongs_to :tweet, optional: true
    belongs_to :tweet_comment, optional: true
    belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
    belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
      #current_userの投稿に紐づいた通知一覧
        @notifications = current_user.passive_notifications.page(params[:page]).per(6)
      #@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
        @notifications.where(checked: false).each do |notification|
            notification.update_attributes(checked: true)
        end
  end

  def destroy
      #通知を全削除
        @notifications = current_user.passive_notifications.destroy_all
        redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_form(notification)
      @visiter = notification.visiter
      @comment = nil
      @tweet = link_to 'あなたの投稿', tweet_path(notification), style:"font-weight: bold;"
      @visiter_tweet_comment = notification.tweet_comment_id
      #notification.actionがfollowかlikeかcommentか
      case notification.action
        when "follow" then
          tag.a(notification.visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"があなたをフォローしました"
        when "favorite" then
          tag.a(notification.visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:tweet_path(notification.tweet_id), style:"font-weight: bold;")+"にいいねしました"
        when "tweet_comment" then
            @comment = TweetComment.find_by(id: @visiter_comment)&.content
            tag.a(@visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:tweet_path(notification.tweet_id), style:"font-weight: bold;")+"にコメントしました"
      end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end


end

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% tweet = notification.tweet %>

<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <table class="table">
      <tr>
        <th><%= link_to user_path(notification.visiter_id) do %>
          <div class="image is-64x64"><%= attachment_image_tag visiter, :profile_image, :fill,60,60, format: "jpeg", fallback: "no_image.jpg",class: "is-rounded" %></div>
          <% end %>
        </th>
        <th>
          <%= notification_form(notification) %><%= " (#{time_ago_in_words(notification.created_at)} 前)" %>
          <% if !@comment.nil? %>
            <%= @comment %>
          <% end %>
          </th>
      </tr>
    </table>
  </div>
</div>

app/views/notifications/index.html.erb
<section class="hero is-small is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        通知
      </h1>
    </div>
  </div>
</section>
    <%= link_to notification_path(@notifications), method: :delete, data: {confirm: "削除しますか？"} do %>
    <div class="button is-success">全削除</div>
    <% end %>
    <% if @notifications.exists? %>
    <%= render @notifications %>
    <% else %>
    <section class="section">
     <div class="container">
      <div class="columns is-centered">
       通知はありません
      </div>
　   </div>
   </section>
    <% end %>
      <div class="columns is-mobile is-centered">
        <div class="column is-half">
          <p class="bd-notification is-primary">
            <%= paginate @notifications %>
          </p>
        </div>
      </div>