config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
 root to: "homes#index"
 get 'homes/about'
 post '/homes/guest_sign_in', to: 'homes#new_guest'
 get 'tweets/search'

 resources :tweets, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
   resource :favorites, only: [:create, :destroy]
   resources :tweet_comments, only: [:create, :destroy]
 end
 resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :following, :followers
      end
    end
 resources :relationships, only: [:create, :destroy]
 resources :notifications, only: [:index, :destroy]


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :tweet_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy


  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end


  validates :name, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです。'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id),notice: 'プロフィールを更新しました。'
    else
      render :edit
    end
  end

  def following
    @user =User.find(params[:id])
    @users =@user.followings.page(params[:page]).per(5)
    render 'index'
  end

  def followers
    @user =User.find(params[:id])
    @users =@user.followers.page(params[:page]).per(5)
    render 'index'
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<section class="hero is-small is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>

<% if @user.errors.any? %>
  <div class="notification is-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <div class="field">
          <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :name, "ユーザー名", class: "label" %>
            <%= f.text_field :name, class: "input" %>
          </div>
           <div class="field">
            <%= f.label :introduction, "プロフィール", class: "label" %>
            <%= f.text_area :introduction, class: "textarea" %>
          </div>
          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>
         <%= f.submit "更新", class: "button is-success" %>
          <% end %>
     </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-small is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <% if controller.action_name == 'index' %>
          ユーザー
        <% elsif controller.action_name == 'following' %>
          フォロー一覧
        <% elsif controller.action_name == 'followers' %>
          フォロワー一覧
        <% end %>
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                 <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, :fill, 256,256, fallback: "no_image.jpg",class: "is-rounded" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.name, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.tweets.count %>
                <%= render "relationships/follow_button", user: user %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-small is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <p class= "image"><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", class: "is-rounded" %></p>
            </figure>
              </div>
                <div class="column is-8">
                  <table class="table is-fullwidth">
                    <tr>
                      <td class="is-size-4">
                        <strong><%= @user.name %></strong>
                      </td>
                      <td>
                        <%= link_to "フォロー(#{@user.followings.count})", following_user_path(@user) %>
                      </td>
                      <td>
                        <%= link_to "フォロワー(#{@user.followers.count})", followers_user_path(@user) %>
                      </td>
                      <td>
                        <% if @user.id == current_user.id %>
                        <div class="button is-outlined"><%= link_to "プロフィール編集", edit_user_path(@user) %></div>
                        <% end %>
                      </td>
                    </tr>
                  </table>
                  <table class="table is-fullwidth">
                    <tr>
                      <td>
                        <%= @user.introduction %>
                      </td>
                    </tr>
                  </table>
               </div>
            </div>
          </div>
       </div>
    </div>
</section>

<section class="section">
   <div class="container">
     <div class="columns is-multiline">
       <% @tweets.each do |tweet| %>
         <div class="column is-4">
           <div class="card">
             <p class="image is-64x64"><%= attachment_image_tag tweet.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",class: "is-rounded" %></p>
             <p><%= tweet.user.name %></p>
             <p class="column is-full"><%= tweet.body %></p>
             <figure class="image is-2by1">
                <%= attachment_image_tag tweet, :image, fallback: "no_image.jpg" %>
              </figure>
              <%= link_to tweet_path(tweet.id), class: "panel-block" do %>
              <span class="panel-icon">
                  <i class="fas fa-book" aria-hidden="true"></i>
              </span>
                つぶやきを見る
              <% end %>
              <% if @user.id == current_user.id %>
              <%= link_to edit_tweet_path(tweet.id), class: "panel-block" do %>
                  <span class="panel-icon">
                      <i class="fas fa-edit"></i>
                  </span>
                    このつぶやきを編集する
              <% end %>
              <%= link_to tweet_path(tweet), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                  <span class="panel-icon">
                      <i class="fas fa-trash"></i>
                  </span>
                    このつぶやきを削除する
              <% end %>
              <% end %>
            </div>
          </div>
          <% end %>
       <%= paginate @tweets %>
    </div>
  </div>
</section>