config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
 root to: "homes#index"
 get 'homes/about'
 post '/homes/guest_sign_in', to: 'homes#new_guest'
 get 'tweets/search'

 resources :tweets, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
   resource :favorites, only: [:create, :destroy]
   resources :tweet_comments, only: [:create, :destroy]
 end
 resources :users, only: [:index, :show, :edit, :update] do
      member do
        get :following, :followers
      end
    end
 resources :relationships, only: [:create, :destroy]
 resources :notifications, only: [:index, :destroy]


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GOODLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if flash[:notice] %>
        <div class="notification is-success is-light">
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="notification is-danger is-light">
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>

      <nav class="navbar">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do  %>
     <h1 class="title is-4" style="font-family: Georgia;">Good Life</h1>
      <% end %>
      </div>
     <div class="tabs">
      <% if user_signed_in? %>
        <%= link_to "投稿一覧", tweets_path, class: "fas fa-image" %>
        <%= link_to "新規投稿", new_tweet_path, class: "fas fa-paper-plane" %>
        <%= link_to "ユーザー覧", users_path, class: "fas fa-users" %>
        <%= link_to "マイページ",user_path(current_user.id), class: "fas fa-user-alt" %>
        <%= link_to "通知", notifications_path, class: "fas fa-bell" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt" %>
      <% else %>
        <%= link_to "ログイン",new_user_session_path, class: "fas fa-sign-in-alt" %>
        <%= link_to "新規登録",new_user_registration_path, class: "fas fa-user-plus" %>
      <% end %>

    </div>
    </nav>

    <%= yield %>
  </body>
</html>